### ISSUE TITLE
alignak_setup?

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-module-snmp-booster#2]
```
/repos/alignak-module-snmp-booster# sudo pip install -v --upgrade .
Processing /root/repos/alignak-module-snmp-booster
  Running setup.py (path:/tmp/pip-4XFNZU-build/setup.py) egg_info for package from file:///root/repos/alignak-module-snmp-booster
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-4XFNZU-build/setup.py", line 7, in <module>
        from alignak_setup.tools import get_alignak_cfg, get_files, get_to_be_installed_files, parse_files
    ImportError: No module named alignak_setup.tools
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4XFNZU-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4XFNZU-build/
```

**Comment by mohierf** [comment]
@spea1 : note that this module has never been tested nor available ... we started some tests with @fpeyre but never ended the job :/

**Comment by fpeyre** [comment]
Yes, I confirm. This module is in progress and doesn't work currently ( It's a shinken module, so we must change some function to use it with Alignak)

Maybe we can add a Flag or something to indicate this information ?

**Comment by mohierf** [comment]
@fpeyre : see https://github.com/Alignak-monitoring-contrib/alignak-module-snmp-booster#warning-this-module-is-still-a-very-draft-version- 😉
